CREATE TABLE KHOAHOC (
    MAKH VARCHAR(5) PRIMARY KEY,
    TENKH VARCHAR(10),
    NGAYBD DATE,
    NGAYKT DATE,
    
    CHECK(NGAYKT > NGAYBD)
    
);

CREATE TABLE CHUONGTRINH (
    MACT VARCHAR(5) PRIMARY KEY,
    TENCT VARCHAR(50) 
);

CREATE TABLE LOAILOP (
    MALOAI VARCHAR(5) PRIMARY KEY,
    MACT VARCHAR(5),
    TENLOAI VARCHAR(50),
    
    CONSTRAINT fk_01 FOREIGN KEY(MACT) REFERENCES CHUONGTRINH(MACT)
    
);

CREATE TABLE LOP (
    MALOP VARCHAR(5) PRIMARY KEY,
    MALOAI VARCHAR(5),
    TENLOP VARCHAR(50),
    SISO INT,
    MAKH VARCHAR(5),
    
    CHECK (SISO > 12),
    
    CONSTRAINT fk_02 FOREIGN KEY(MALOAI) REFERENCES LOAILOP(MALOAI),
                     FOREIGN KEY(MAKH) REFERENCES KHOAHOC(MAKH)
);

CREATE TABLE HOCVIEN (
    MALHV VARCHAR(5) PRIMARY KEY,
    TENHV VARCHAR(50),
    GIOITINH NUMBER(1),
    NGAYSINH DATE,
    SDT VARCHAR(15),
    DIACHI VARCHAR(125),
    
    CHECK (GIOITINH = 0 OR GIOITINH = 1)
    
);

CREATE TABLE ZPHIEUTHU (
    SOPT VARCHAR(10) PRIMARY KEY,
    MAHV VARCHAR(5),
    MALOP VARCHAR(5),
    NGAYLAYPHIEU DATE,
    THANHTIEN NUMBER(10),
    
    CHECK (THANHTIEN > 0),
    
    CONSTRAINT fk_03 FOREIGN KEY(MAHV) REFERENCES ZHOCVIEN(MAHV),
                     FOREIGN KEY(MALOP) REFERENCES ZLOP(MALOP)
);

CREATE TABLE ZMONHOC (
    MAMH VARCHAR (5) PRIMARY KEY,
    TENMH VARCHAR(10)  
);

CREATE TABLE ZDIEM (
    MAMH VARCHAR(5) NOT NULL,
    MAHV VARCHAR(5) NOT NULL,
    MALOP VARCHAR(5) NOT NULL,
    DIEM FLOAT CHECK(DIEM >= 0 AND DIEM <= 10),
    
    CONSTRAINT fk_04 FOREIGN KEY(MAMH) REFERENCES ZMONHOC(MAMH),
                     FOREIGN KEY(MAHV) REFERENCES ZHOCVIEN(MAHV),
                     FOREIGN KEY(MALOP) REFERENCES ZLOP(MALOP),
                     
    PRIMARY KEY(MAMH, MAHV, MALOP)
);


INSERT INTO ZKHOAHOC(makh, tenkh, ngaybd, ngaykt)
VALUES
    ('K001', 'Khóa 1', TO_DATE('2020-01-10', 'YYYY-MM-DD'), TO_DATE('2020-03-20', 'YYYY-MM-DD')),
    ('K002', 'Khóa 2', TO_DATE('2020-02-28', 'YYYY-MM-DD'), TO_DATE('2020-05-28', 'YYYY-MM-DD')),
    ('K003', 'Khóa 3', TO_DATE('2020-04-10', 'YYYY-MM-DD'), TO_DATE('2020-07-20', 'YYYY-MM-DD')),
    ('K004', 'Khóa 4', TO_DATE('2020-06-15', 'YYYY-MM-DD'), TO_DATE('2020-09-20', 'YYYY-MM-DD'));











